#Referred from https://github.com/ngeri/actions-ios/blob/master/.github/workflows/feature_pipeline.yml
name: Release Workflow

on: 
  push:
    tags:
    - v[0-9].[0-9].[0-9]

jobs:
  build:
    name: Build & Upload(Testflight)
    env:
      SCHEME: "MyTVML"
      DEVICE: "Apple TV 4K"
      DERIVED_DATA_PATH: "DerivedData"
    runs-on: macOS-latest
    steps:
    - name: Checkout project
      uses: actions/checkout@v1
    - name: Build application
      run: |
        set -o pipefail && xcodebuild clean -scheme $SCHEME -destination "platform=tvOS Simulator,name=$DEVICE" -derivedDataPath $DERIVED_DATA_PATH build-for-testing | xcpretty --color --simple
    - name: Upload products
      uses: actions/upload-artifact@v1
      with:
        name: Products
        path: DerivedData/Build/Products
